### ISSUE TITLE
Correct multiple PHP warnings when the module isn't installed

### ISSUE THREAD

**Issue by lat9** [njcyx/fedexsmartpost#1]
Change this line
https://github.com/njcyx/fedexsmartpost/blob/bd1df834fc2dd74585cee9d34dacc8e2c69bed1a/includes/modules/shipping/fedexsmartpost.php#L17

to read:
```php
        $this->sort_order = (defined('MODULE_SHIPPING_FEDEX_SMARTPOST_SORT_ORDER')) ? (int)MODULE_SHIPPING_FEDEX_SMARTPOST_SORT_ORDER: null;
        if ($this->sort_order === null) {
            return false;
        }
```

**Comment by njcyx** [comment]
Hi @lat9 , you saved my day! 

I just tried and suggestion and it worked perfectly! No more warning! Thanks!

Code updated.
