### ISSUE TITLE
PHP `strftime` deprecated as of PHP 8.1

### ISSUE THREAD

**Issue by lat9** [njcyx/fedexsmartpost#3]
There are also a couple of places where dates are formatted via PHP's `strftime` function, which is deprecated as of PHP 8.1 and will lead to many PHP Deprecated logs if used in that or later PHP versions.  Actually, for PHP 8.2, those will result in PHP Error logs.

**Comment by njcyx** [comment]
Code updated. Thanks. I changed to use date() instead.
